"""add_payments_table_and_pending_payment_status

Revision ID: 4abe05ed05b4
Revises: b2d54a525fd0
Create Date: 2025-11-25 11:20:37.508645

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4abe05ed05b4"
down_revision: Union[str, None] = "b2d54a525fd0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import inspect

    conn = op.get_bind()
    inspector = inspect(conn)
    existing_tables = inspector.get_table_names()

    # Only create audit_logs if it doesn't exist (it was created in initial migration)
    if "audit_logs" not in existing_tables:
        op.create_table(
            "audit_logs",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("user_id", sa.Integer(), nullable=True),
            sa.Column("action", sa.String(), nullable=False),
            sa.Column("resource_type", sa.String(), nullable=False),
            sa.Column("resource_id", sa.Integer(), nullable=True),
            sa.Column("details", sa.JSON(), nullable=True),
            sa.Column("ip_address", sa.String(), nullable=True),
            sa.Column("user_agent", sa.String(), nullable=True),
            sa.Column("timestamp", sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(
                ["user_id"],
                ["users.id"],
            ),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index(
            op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False
        )
        op.create_index(op.f("ix_audit_logs_id"), "audit_logs", ["id"], unique=False)
        op.create_index(
            op.f("ix_audit_logs_timestamp"), "audit_logs", ["timestamp"], unique=False
        )

    # Create payments table (this is new in this migration)
    op.create_table(
        "payments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("bid_id", sa.Integer(), nullable=False),
        sa.Column("stripe_payment_intent_id", sa.String(length=255), nullable=False),
        sa.Column("stripe_charge_id", sa.String(length=255), nullable=True),
        sa.Column("amount", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column(
            "payment_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["bid_id"],
            ["bids.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("bid_id"),
        sa.UniqueConstraint("stripe_payment_intent_id"),
    )
    op.create_index("idx_payments_bid_id", "payments", ["bid_id"], unique=False)
    op.create_index("idx_payments_created_at", "payments", ["created_at"], unique=False)
    op.create_index("idx_payments_status", "payments", ["status"], unique=False)
    op.create_index(
        "idx_payments_stripe_payment_intent_id",
        "payments",
        ["stripe_payment_intent_id"],
        unique=False,
    )
    op.create_index(op.f("ix_payments_id"), "payments", ["id"], unique=False)

    # Check for existing columns and indexes before adding
    artwork_columns = [col["name"] for col in inspector.get_columns("artworks")]
    artwork_indexes = [idx["name"] for idx in inspector.get_indexes("artworks")]
    bid_columns = [col["name"] for col in inspector.get_columns("bids")]
    bid_indexes = [idx["name"] for idx in inspector.get_indexes("bids")]

    # Add artwork columns if they don't exist (they may have been added in b2d54a525fd0)
    if "artist_name" not in artwork_columns:
        op.add_column("artworks", sa.Column("artist_name", sa.String(), nullable=True))
    if "category" not in artwork_columns:
        op.add_column("artworks", sa.Column("category", sa.String(), nullable=True))
    if "end_date" not in artwork_columns:
        op.add_column(
            "artworks", sa.Column("end_date", sa.DateTime(timezone=True), nullable=True)
        )

    # Add artwork indexes if they don't exist
    if "ix_artworks_category" not in artwork_indexes:
        op.create_index(
            op.f("ix_artworks_category"), "artworks", ["category"], unique=False
        )
    if "ix_artworks_seller_id" not in artwork_indexes:
        op.create_index(
            op.f("ix_artworks_seller_id"), "artworks", ["seller_id"], unique=False
        )
    if "ix_artworks_status" not in artwork_indexes:
        op.create_index(
            op.f("ix_artworks_status"), "artworks", ["status"], unique=False
        )

    # Handle bids table - add created_at if it doesn't exist, drop bid_time if it exists
    if "created_at" not in bid_columns:
        op.add_column(
            "bids",
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=True,
            ),
        )

    # Add bid indexes if they don't exist
    if "ix_bids_artwork_id" not in bid_indexes:
        op.create_index(
            op.f("ix_bids_artwork_id"), "bids", ["artwork_id"], unique=False
        )
    if "ix_bids_bidder_id" not in bid_indexes:
        op.create_index(op.f("ix_bids_bidder_id"), "bids", ["bidder_id"], unique=False)

    # Drop bid_time if it still exists
    if "bid_time" in bid_columns:
        op.drop_column("bids", "bid_time")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import inspect

    conn = op.get_bind()
    inspector = inspect(conn)

    bid_columns = [col["name"] for col in inspector.get_columns("bids")]

    # Restore bids table changes
    if "bid_time" not in bid_columns:
        op.add_column(
            "bids",
            sa.Column(
                "bid_time",
                postgresql.TIMESTAMP(timezone=True),
                server_default=sa.text("now()"),
                autoincrement=False,
                nullable=True,
            ),
        )
    op.drop_index(op.f("ix_bids_bidder_id"), table_name="bids", if_exists=True)
    op.drop_index(op.f("ix_bids_artwork_id"), table_name="bids", if_exists=True)
    if "created_at" in bid_columns:
        op.drop_column("bids", "created_at")

    # Restore artworks table changes
    op.drop_index(op.f("ix_artworks_status"), table_name="artworks", if_exists=True)
    op.drop_index(op.f("ix_artworks_seller_id"), table_name="artworks", if_exists=True)
    op.drop_index(op.f("ix_artworks_category"), table_name="artworks", if_exists=True)

    artwork_columns = [col["name"] for col in inspector.get_columns("artworks")]
    if "end_date" in artwork_columns:
        op.drop_column("artworks", "end_date")
    if "category" in artwork_columns:
        op.drop_column("artworks", "category")
    if "artist_name" in artwork_columns:
        op.drop_column("artworks", "artist_name")

    # Drop payments table (always - this is new in this migration)
    op.drop_index(op.f("ix_payments_id"), table_name="payments")
    op.drop_index("idx_payments_stripe_payment_intent_id", table_name="payments")
    op.drop_index("idx_payments_status", table_name="payments")
    op.drop_index("idx_payments_created_at", table_name="payments")
    op.drop_index("idx_payments_bid_id", table_name="payments")
    op.drop_table("payments")

    # Only drop audit_logs if this migration created it (not if it existed from initial migration)
    existing_tables = inspector.get_table_names()
    if "audit_logs" in existing_tables:
        # Check if we should drop it - only if this migration created it
        # In practice, we skip dropping audit_logs since it was in the initial migration
        pass
    # ### end Alembic commands ###
